### PR TITLE
Feature/event

### PR DESCRIPTION
**Pull request by aabounegm**

### CODE REVIEW

**Comment by illright** [comment]
image
The name of the event should be aligned with the contents, such as the date icon

**Comment by illright** [comment]
image
Make equal spacing from the top and from the left for the heading

**Comment by illright** [comment]
image
The icon should be aligned with the baseline of the text

**Comment by illright** [comment]
image
The vertical space between cards should be ever-so-slightly less than the horizontal space

**Comment by illright** [comment]
image
The buttons should have `.shadow-1`

**Comment by illright** [comment]
image
The buttons should always stick to the bottom of the card

**Comment by illright** [comment]
image
The activities should not be limited in height by the button. Look into `float`.

**Comment by illright** [comment]
image
Increase the margin from the filter

**Comment by illright** [comment]
image
Now THAT's one big search bar. Please, isolate all your styles by prepending the class of the block you're working on to the selector :)

**Comment by illright** [comment]
image
Also I hardly see any improvement here. Maybe I phrased the issue poorly. The vertical space between the cards should be almost similar to the horizontal space. Also, the horizontal space is too big

**Comment by illright** [comment]
The card headings should not be centered, idk why it is this way now

**Comment by illright** [comment]
Also, if you're going to write styles for wide screens, it might be a good idea to remove `.container` from `.events` :p

**Comment by illright** [comment]
image
I've signed up for a regular grid, not this funky alignment)

**Comment by illright** [comment]
image
Ew, three lines for a heading

**Comment by aabounegm** [comment]
> Ew, three lines for a heading

You went to the border case. It switches to mobile size at 640px. We can either set the breakpoint a little higher or decrease the heading size.

**Pull request merged**
